### PR TITLE
[Dataeng-1099] - initial terraform structure

### PR DESCRIPTION
**Pull request by caiopavanelli**
## Motivation and context for the change
https://loadsmart.atlassian.net/browse/DATAENG-1099

Initial terraform config. The website should be exposed under analytics.loadsmart.com

Setups:

- QA, Staging, Sandbox & Prod environments
- S3 Bucket
- Cloudfront CDN
- DNS
- Sentry Project
- CircleCI Env
- Secrets

## A clear description of the change

see above.

## Testing

n/a

- [ ] The change is covered with automated tests

#### Testing instructions

n/a

## Rollback

- [ ] The change can be automatically rolled back

#### Rollback instructions

undo changes

### CODE REVIEW

**Review by luiz-cesa — APPROVED** [review]

**Review by cesar-loadsmart — APPROVED** [review]
LGTM!

**Review by lenoirzamboni — APPROVED** [review]

**Comment by mwconceicao** [comment]
atlantis approve_policies

**Comment by caiopavanelli** [comment]
atlantis apply -p general

**Comment by mwconceicao** [comment]
atlantis approve_policies

**Comment by caiopavanelli** [comment]
atlantis apply -p general

**Comment by caiopavanelli** [comment]
atlantis apply -p qa

**Comment by caiopavanelli** [comment]
atlantis apply

**Pull request merged**
